"""AlphaZero-style self-play loop.

Each self-play game is generated by a Neural-MCTS agent that uses the
current network to score positions. Visit counts at the root produce
policy targets; the final game outcome (win/lose) produces value targets.

Training is a standard supervised step:
  loss = cross_entropy(policy, π_mcts) + (value - z)^2

This module provides the loop; tune iterations / batch size for your hardware."""

from __future__ import annotations

import argparse
import math
import random
from dataclasses import dataclass
from typing import List, Optional

import numpy as np

from agents.base import BaseAgent
from agents.expectimax_agent import ExpectimaxAgent
from game import GameConfig, GameEngine
from game.cards import CardKind
from game.state import GameState

from .encoder import FEATURE_DIM, encode_state


@dataclass
class TrainingExample:
    features: np.ndarray  # shape (FEATURE_DIM,)
    policy: np.ndarray    # shape (2,) — [P(draw), P(fold)]
    value: float          # final outcome from this player's POV in [-1, 1]


class NeuralMCTSAgent(BaseAgent):
    """PUCT-style MCTS with a network for prior + leaf value.

    For self-play, set `dirichlet_eps > 0` to inject exploration noise at the root."""

    name = "neural_mcts"

    def __init__(
        self,
        model=None,
        n_simulations: int = 200,
        c_puct: float = 1.5,
        dirichlet_eps: float = 0.0,
        dirichlet_alpha: float = 0.5,
        rollout_factory=None,
        seed: Optional[int] = None,
    ) -> None:
        self.model = model
        self.n_sims = n_simulations
        self.c_puct = c_puct
        self.dir_eps = dirichlet_eps
        self.dir_alpha = dirichlet_alpha
        self.rollout_factory = rollout_factory or (lambda: ExpectimaxAgent(depth=2))
        self.rng = random.Random(seed)
        self._last_visits: Optional[np.ndarray] = None  # exposed for training

    def policy_and_value(self, state: GameState, my_idx: int):
        if self.model is None:
            # uniform prior, neutral value
            return np.array([0.5, 0.5], dtype=np.float32), 0.0
        import torch
        x = torch.from_numpy(encode_state(state, my_idx)).unsqueeze(0)
        with torch.no_grad():
            logits, v = self.model(x)
            p = torch.softmax(logits, dim=-1).numpy()[0]
        return p, float(v.item())

    def choose_action(self, state: GameState, my_idx: int) -> str:
        me = state.players[my_idx]
        cur = sum(me.hand_numbers) + me.bonus_flat_total
        if me.total_score + cur >= state.config.target_score:
            self._last_visits = np.array([0.0, 1.0], dtype=np.float32)
            return "fold"

        prior, _ = self.policy_and_value(state, my_idx)
        if self.dir_eps > 0:
            noise = np.random.dirichlet([self.dir_alpha] * 2)
            prior = (1 - self.dir_eps) * prior + self.dir_eps * noise

        from agents.mcts_agent import _hollow_engine

        N = np.zeros(2, dtype=np.float32)
        W = np.zeros(2, dtype=np.float32)

        actions = ["draw", "fold"]
        for _ in range(self.n_sims):
            # PUCT
            total_visits = N.sum() + 1
            ucb = (W / np.maximum(N, 1)) + self.c_puct * prior * math.sqrt(total_visits) / (1 + N)
            a_idx = int(np.argmax(ucb))
            r = self._simulate(state, my_idx, actions[a_idx])
            N[a_idx] += 1
            W[a_idx] += r

        # use visit counts as policy target
        self._last_visits = N / max(N.sum(), 1)
        # choose best by visit count (greedy for evaluation; sample for self-play if you want)
        return actions[int(np.argmax(N))]

    def choose_skill_target(self, state, my_idx, kind):
        from .encoder import encode_state  # noqa
        from agents.ev_agent import EVAgent
        return EVAgent().choose_skill_target(state, my_idx, kind)

    # --------------------------------------------------------- internal sim
    def _simulate(self, state: GameState, my_idx: int, action: str) -> float:
        from agents.mcts_agent import _hollow_engine
        rollout_agents = [self.rollout_factory() for _ in range(state.config.num_players)]
        host = _hollow_engine(state)
        sim = host.clone_for_simulation(rollout_agents, rng_seed=self.rng.randint(0, 1 << 30))
        sim.state.current_player = my_idx
        if action == "fold":
            from game.state import PlayerStatus
            me = sim.state.players[my_idx]
            me.locked_round_score = sum(me.hand_numbers) + me.bonus_flat_total
            me.status = PlayerStatus.FOLDED
            sim.state.last_actor = my_idx
        else:
            sim._draw_for(my_idx)
            sim.state.last_actor = my_idx
        if not sim.state.round_over:
            sim._advance_turn()
            sim.play_round_to_completion()
        else:
            sim._settle_round()
        if not sim.state.game_over:
            sim.play_round()

        # leaf value (use NN if available — bootstrapped value)
        if not sim.state.game_over and self.model is not None:
            _, v = self.policy_and_value(sim.state, my_idx)
            return v

        if sim.state.game_over:
            return 1.0 if sim.state.winner == my_idx else -1.0
        target = sim.state.config.target_score
        me_total = sim.state.players[my_idx].total_score
        others = max(p.total_score for p in sim.state.players if p.index != my_idx)
        return max(-1.0, min(1.0, (me_total - others) / target))


# ============================================================== self-play
def play_one_game(model, n_simulations: int = 100, num_players: int = 4,
                   use_batched: bool = True, batch_size: int = 32,
                   device: str = "cpu") -> List[TrainingExample]:
    """Run a self-play match where all 4 seats use a Neural-MCTS agent.

    use_batched=True (default) uses the much faster BatchedNeuralMCTSAgent
    which collects leaf states across virtual-loss-spread sims and evaluates
    them in a single batched forward pass."""
    cfg = GameConfig(num_players=num_players)
    if use_batched:
        from agents.batched_mcts import BatchedNeuralMCTSAgent
        # AlphaZero-style exploration during self-play: dirichlet noise at root,
        # temperature=1 for visit-count sampling, plus hybrid leaf eval that
        # blends NN value with handcrafted EV signal — the EV teacher accelerates
        # value-head bootstrapping in the small-data regime.
        agents = [BatchedNeuralMCTSAgent(model=model,
                                          n_simulations=n_simulations,
                                          batch_size=batch_size,
                                          dirichlet_eps=0.25,
                                          dirichlet_alpha=0.5,
                                          temperature=1.0,
                                          hybrid_alpha=0.5,
                                          device=device)
                   for _ in range(num_players)]
    else:
        agents = [NeuralMCTSAgent(model=model, n_simulations=n_simulations,
                                   dirichlet_eps=0.25) for _ in range(num_players)]
    engine = GameEngine(cfg, agents)
    pending: list[tuple[np.ndarray, np.ndarray, int]] = []  # (features, policy, my_idx)

    # Wrap engine to record pre-action features and visit counts.
    orig_take = engine._take_turn

    def recording_take(idx: int):
        if engine.state.players[idx].is_active:
            x = encode_state(engine.state, idx)
            orig_take(idx)
            pi = agents[idx]._last_visits
            if pi is not None:
                pending.append((x, np.array(pi, dtype=np.float32), idx))
        else:
            orig_take(idx)

    engine._take_turn = recording_take  # monkey-patch
    engine.play_match()
    winner = engine.state.winner
    # Placement-based value target (Petosa & Balch, Multiplayer AlphaZero):
    # 1st → +1, 2nd → +1/3, 3rd → −1/3, 4th → −1.
    # Lower variance than binary winner-takes-all and gives a learnable signal
    # to all 4 players, not just the winner.
    final_totals = [p.total_score for p in engine.state.players]
    rank = sorted(range(num_players), key=lambda i: -final_totals[i])  # idx by desc score
    placement_z = [0.0] * num_players
    # Asymmetric placement: only 1st place is "good", everyone else is bad.
    # Rationale: the game is winner-takes-all (target_score 200), so optimizing
    # for "avoid last place" (symmetric +1/+1/3/-1/3/-1) trains agents to fold
    # for safety, never reaching the target. Asymmetric reward keeps lower
    # variance than binary ±1 while pointing the value head at the right goal.
    placement_values = [1.0, -1/3, -2/3, -1.0]
    for pos, idx in enumerate(rank):
        placement_z[idx] = placement_values[pos] if pos < 4 else -1.0
    examples: List[TrainingExample] = []
    for x, pi, idx in pending:
        examples.append(TrainingExample(features=x, policy=pi,
                                          value=placement_z[idx]))
    return examples


def train_step(model, optimizer, batch: List[TrainingExample], device: str = "cpu"):
    import torch
    X = torch.from_numpy(np.stack([b.features for b in batch])).to(device)
    P = torch.from_numpy(np.stack([b.policy for b in batch])).to(device)
    Z = torch.from_numpy(np.array([b.value for b in batch], dtype=np.float32)).to(device)
    logits, v = model(X)
    log_p = torch.log_softmax(logits, dim=-1)
    policy_loss = -(P * log_p).sum(dim=-1).mean()
    value_loss = ((v - Z) ** 2).mean()
    loss = policy_loss + value_loss
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    return float(policy_loss.detach()), float(value_loss.detach())


# ============================================================ multiprocessing
def _worker_play(weights_bytes: bytes, n_games: int, n_sims: int, seed: int,
                  device: str = "cpu") -> List[TrainingExample]:
    """Worker entry: rebuild model from serialized weights, play N games."""
    import io
    import random as _random
    import torch
    torch.set_num_threads(1)  # workers shouldn't fight each other for CPU
    _random.seed(seed)
    np.random.seed(seed & 0xFFFFFFFF)
    from .network import build_model
    model = build_model()
    model.load_state_dict(torch.load(io.BytesIO(weights_bytes), map_location="cpu"))
    if device != "cpu":
        try:
            model = model.to(device)
        except Exception as e:
            print(f"⚠ worker failed to move model to {device}: {e}; falling back to cpu")
            device = "cpu"
    model.eval()
    out: List[TrainingExample] = []
    for _ in range(n_games):
        out.extend(play_one_game(model, n_simulations=n_sims, device=device))
    return out


def parallel_self_play(model, n_workers: int, total_games: int, n_sims: int,
                        base_seed: int = 0, device: str = "cpu") -> List[TrainingExample]:
    """Distribute `total_games` across `n_workers` spawn workers."""
    import io
    import multiprocessing as mp
    import torch
    buf = io.BytesIO()
    # 保存到 CPU 字节流便于传给 worker
    cpu_state = {k: v.cpu() for k, v in model.state_dict().items()}
    torch.save(cpu_state, buf)
    weights = buf.getvalue()

    games_per = [total_games // n_workers] * n_workers
    for i in range(total_games % n_workers):
        games_per[i] += 1

    ctx = mp.get_context("spawn")
    args = [(weights, g, n_sims, base_seed + i, device) for i, g in enumerate(games_per) if g > 0]
    examples: List[TrainingExample] = []
    with ctx.Pool(processes=len(args)) as pool:
        for chunk in pool.starmap(_worker_play, args):
            examples.extend(chunk)
    return examples


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--iters", type=int, default=20, help="self-play / train iterations")
    parser.add_argument("--games-per-iter", type=int, default=8)
    parser.add_argument("--n-sims", type=int, default=80)
    parser.add_argument("--workers", type=int, default=6,
                        help="parallel self-play workers; 0 = serial")
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--out", default="model.pt")
    parser.add_argument("--resume", default=None,
                        help="path to existing model checkpoint to continue from")
    parser.add_argument("--device", default="cpu",
                        help="cpu / mps / cuda — 实测 30K 小网络 + batch=1 推理 CPU 通常更快")
    args = parser.parse_args()

    import time

    import torch
    from .network import build_model, save

    model = build_model()
    if args.resume:
        model.load_state_dict(torch.load(args.resume, map_location="cpu"))
        print(f"Resumed from {args.resume}")
    if args.device != "cpu":
        try:
            model = model.to(args.device)
            print(f"Model on {args.device}")
        except Exception as e:
            print(f"⚠ failed to move model to {args.device}: {e}; falling back to cpu")
            args.device = "cpu"
    optimizer = torch.optim.Adam(model.parameters(), lr=args.lr)

    buffer: list[TrainingExample] = []
    for it in range(args.iters):
        t0 = time.time()
        if args.workers > 0:
            new_examples = parallel_self_play(
                model, n_workers=args.workers,
                total_games=args.games_per_iter,
                n_sims=args.n_sims,
                base_seed=it * 1000,
                device=args.device,
            )
            buffer.extend(new_examples)
        else:
            for _ in range(args.games_per_iter):
                buffer.extend(play_one_game(model, n_simulations=args.n_sims,
                                              device=args.device))
        sp_time = time.time() - t0
        # sample
        if len(buffer) > 8192:
            buffer = buffer[-8192:]
        random.shuffle(buffer)
        # one epoch
        bs = 64
        pl = vl = 0.0
        nbat = 0
        t1 = time.time()
        for i in range(0, len(buffer), bs):
            chunk = buffer[i:i + bs]
            if len(chunk) < 4:
                continue
            p, v = train_step(model, optimizer, chunk, device=args.device)
            pl += p
            vl += v
            nbat += 1
        train_time = time.time() - t1
        print(f"iter {it+1}/{args.iters}  buf={len(buffer)}  "
              f"sp={sp_time:.1f}s ({args.games_per_iter/max(sp_time,0.01):.1f} g/s)  "
              f"train={train_time:.1f}s  "
              f"policy_loss={pl/max(nbat,1):.3f}  value_loss={vl/max(nbat,1):.3f}")
        save(model, args.out)


if __name__ == "__main__":
    main()
